identity:
  name: yidun-text-security
  author: yidun
  label:
    en_US: textSecurity
    zh_Hans: 易盾内容安全文本检测
    pt_BR: textSecurity
description:
  human:
    en_US: A tool for detecting whether the input content violates/meets regulatory requirements. The input should be text to be detected/images to be detected.
    zh_Hans: 一个用于检测输入内容是否违规/符合监管要求的工具，输入应为待检测文本。
    pt_BR: A tool for detecting whether the input content violates/meets regulatory requirements. The input should be text to be detected/images to be detected.
  llm: A tool for detecting whether the input content violates/meets regulatory requirements. The input should be text to be detected/images to be detected.
parameters:
  - name: text_content
    type: string
    required: false
    label:
      en_US: Text detection content
      zh_Hans: 文本检测内容
      pt_BR: Text detection content
    human_description:
      en_US: The text to be detected
      zh_Hans: 用于传入文本待检测内容
      pt_BR: The text to be detected
    llm_description: The text to be detected
    form: llm
extra:
  python:
    source: tools/yidun-text-security.py
